name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: 3.9

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set python with  ${{ matrix.python_version }} version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Creating and activating virtualenv
        run: |
          poetry install
          poetry shell

      - name: Test API
        run: |
          pytest tests/api_tests.py