name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.9]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set python with  ${{ matrix.python_version }} version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Creating and activating virtualenv
        run: |
          poetry install --no-interaction

      - name: Test API
        run: |
          source .venv/bin/activate
          pytest tests/api_tests.py